### ISSUE TITLE
Running "vertigo" after installation fails

### ISSUE THREAD

**Issue by jhenkins** [apamment/vertigo-bbs#2]
When running the "vertigo" tool after installation, it fails with the following error:

ERROR: Default theme prompts not found: default.txt

From the looks of it, it could be any number of things. Here are some ideas going through my noggin at the moment (which is going to show how little I know about Mystic in general):

1. It cannot find the actual file, even though it is present in the data directory.
2. It cannot find the theme prompts in the actual file
3. It cannot find material referred to by entries in the default.txt file

**Comment by apamment** [comment]
it's because the default theme isn't defined in the theme.dat file from vertigo -cfg, I thought I had fixed it, but was very late when I committed last night. It's fixed now.
